### ISSUE TITLE
Add "Go Go Jenkins!"

### ISSUE THREAD

**Issue by moio** [MalloZup/gitbot#12]
It's sometimes handy to re-trigger Jenkins jobs manually, and a convenient way is a magic comment like Salt developers do:

https://github.com/saltstack/salt/pull/41235#issuecomment-301559131

**Comment by MalloZup** [comment]
https://github.com/openSUSE/gitbot/issues/1, migrated to upstream project

**Comment by MalloZup** [comment]
@moio https://github.com/openSUSE/gitbot/issues/1 fixed
